# Redes Neuronales Artificiales

Predecir si un cliente abandona o no el banco

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importar el data set

In [2]:
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
dataset.sample(5)

RowNumber  CustomerId  Surname  CreditScore Geography  Gender  Age  \
7691       7692    15791045     Boni          568    France  Female   38   
5756       5757    15706217      Kao          645   Germany    Male   28   
6835       6836    15618391    Doyle          810    France    Male   33   
9890       9891    15670427    Chidi          662     Spain    Male   37   
2202       2203    15751788  Johnson          850     Spain    Male   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
7691       3  132951.92              1          0               1   
5756       7  117466.03              2          1               1   
6835       6       0.00              2          1               1   
9890       4  155187.30              1          1               0   
2202       9   97408.03              1          1               1   

      EstimatedSalary  Exited  
7691        124486.28       0  
5756         34490.06       0  
6835         77965.67       0  
9890         48930.80       0  
2202        175853.64       0

In [7]:
type(X)

numpy.ndarray

In [8]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

## Parte 1 - Pre procesado de datos

Codificar datos categóricos

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],   
    remainder='passthrough'                        
)
X = onehotencoder.fit_transform(X)
X = X[:, 1:]

In [12]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

## Dividir el data set en conjunto de entrenamiento y conjunto de testing

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Escalado de variables

In [14]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

## Parte 2 - Construir la RNA

Importar Keras y librerías adicionales

In [15]:
import keras
from keras.models import Sequential
from keras.layers import Dense

## Inicializar la RNA

In [16]:
classifier = Sequential()

## Añadir las capas de entrada y primera capa oculta

In [17]:
classifier.add(Dense(units = 6, kernel_initializer = "uniform", activation = "relu", input_dim = 11))

## Añadir la segunda capa oculta

In [18]:
classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu"))

## Añadir la capa de salida

In [19]:
classifier.add(Dense(units = 1, kernel_initializer = "uniform",  activation = "sigmoid"))

## Compilar la RNA

In [20]:
classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

## Ajustamos la RNA al Conjunto de Entrenamiento

In [21]:
classifier.fit(X_train, y_train,  batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 806us/step - loss: 0.4878 - accuracy: 0.7952
Epoch 2/100
800/800 [==============================] - 1s 780us/step - loss: 0.4287 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 813us/step - loss: 0.4236 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 773us/step - loss: 0.4196 - accuracy: 0.8179
Epoch 5/100
800/800 [==============================] - 1s 784us/step - loss: 0.4171 - accuracy: 0.8261
Epoch 6/100
800/800 [==============================] - 1s 776us/step - loss: 0.4146 - accuracy: 0.8281
Epoch 7/100
800/800 [==============================] - 1s 832us/step - loss: 0.4129 - accuracy: 0.8300
Epoch 8/100
800/800 [==============================] - 1s 763us/step - loss: 0.4114 - accuracy: 0.8329
Epoch 9/100
800/800 [==============================] - 1s 842us/step - loss: 0.4098 - accuracy: 0.8357
Epoch 10/100
800/800 [==============================] - 1s 847us/step - l

800/800 [==============================] - 1s 892us/step - loss: 0.3997 - accuracy: 0.8349
Epoch 80/100
800/800 [==============================] - 1s 794us/step - loss: 0.3996 - accuracy: 0.8356
Epoch 81/100
800/800 [==============================] - 1s 798us/step - loss: 0.4000 - accuracy: 0.8350
Epoch 82/100
800/800 [==============================] - 1s 782us/step - loss: 0.3995 - accuracy: 0.8341
Epoch 83/100
800/800 [==============================] - 1s 829us/step - loss: 0.4002 - accuracy: 0.8353
Epoch 84/100
800/800 [==============================] - 1s 828us/step - loss: 0.3994 - accuracy: 0.8330
Epoch 85/100
800/800 [==============================] - 1s 795us/step - loss: 0.3997 - accuracy: 0.8346
Epoch 86/100
800/800 [==============================] - 1s 784us/step - loss: 0.3993 - accuracy: 0.8346
Epoch 87/100
800/800 [==============================] - 1s 779us/step - loss: 0.3993 - accuracy: 0.8340
Epoch 88/100
800/800 [==============================] - 1s 797us/step - loss:

## Parte 3 - Evaluar el modelo y calcular predicciones finales

Predicción de los resultados con el Conjunto de Testing

In [22]:
y_pred  = classifier.predict(X_test)
y_pred = (y_pred>0.5)

63/63 [==============================] - 0s 767us/step


Elaborar una matriz de confusión

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

## Parte 4 - Evaluar, mejorar y Ajustar la RNA

Evaluar la RNA

In [24]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [25]:
def build_classifier():
  classifier = Sequential()
  classifier.add(Dense(units = 6, kernel_initializer = "uniform", activation = "relu", input_dim = 11))
  classifier.add(Dense(units = 6, kernel_initializer = "uniform", activation = "relu"))
  classifier.add(Dense(units = 1, kernel_initializer = "uniform", activation = "sigmoid"))
  classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
  return classifier

In [26]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch = 100)
accuracies = cross_val_score(estimator=classifier, X = X_train, y = y_train, cv = 10, n_jobs=-1, verbose = 1)

C:\Windows\Temp\ipykernel_2588\1157864180.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch = 100)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   6 out of  10 | elapsed:    5.0s remaining:    3.3s
[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:    6.3s finished


In [27]:
mean = accuracies.mean()
variance = accuracies.std()

## Mejorar la RNA

Regularización de Dropout para evitar el overfitting

## Ajustar la RNA

In [28]:
from sklearn.model_selection import GridSearchCV

In [29]:
def build_classifier(optimizer):
  classifier = Sequential()
  classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu", input_dim = 11))
  classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu"))
  classifier.add(Dense(units = 1, kernel_initializer = "uniform",  activation = "sigmoid"))
  classifier.compile(optimizer = optimizer, loss = "binary_crossentropy", metrics = ["accuracy"])
  return classifier

In [30]:
classifier = KerasClassifier(build_fn = build_classifier)

C:\Windows\Temp\ipykernel_2588\3867060546.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  classifier = KerasClassifier(build_fn = build_classifier)


In [31]:
parameters = {
    'batch_size' : [25,32],
    'nb_epoch' : [100, 500], 
    'optimizer' : ['adam', 'rmsprop']
}

In [ ]:
---
grid_search = GridSearchCV(estimator = classifier, 
                           param_grid = parameters, 
                           scoring = 'accuracy', 
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_
---